version: 1
disable_existing_loggers: False
formatters:
  normal:
    format: "[%(levelname)-8s - %(asctime)s] %(message)s (%(threadName)s - %(filename)s: %(lineno)d)"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: normal
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]
