# logging模块日志输出配置
version: 1
disable_existing_loggers: False
formatters:
  normal:
    format: "[%(levelname)-8s - %(asctime)s] %(message)s (%(threadName)s - %(filename)s: %(lineno)d)"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: normal
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: normal
    filename: chronos.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
root:
  level: DEBUG
  handlers: [console, file]
