openapi: 3.0.0
info:
  title: Chronos Openapi Document
  version: 1.0.0
servers:
  - url: https://example.com/v1
    description: example
tags:
  - name: Node
    description: 节点相关的openapi接口
  - name: Block
    description: 区块相关的openapi接口
  - name: Transaction
    description: 交易相关的openapi接口
  - name: Address
    description: 地址相关的openapi接口
paths:
  /node/status:
    get:
      tags:
        - Node
      summary: 获取节点状态
      description: 调用该接口， 获取当前节点的运行状态
      operationId: getNodeStatus
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NodeStatus'
  /block/height/{height}:
    get:
      tags:
        - Block
      parameters:
        - name: height
          in: path
          description: 所需获取区块的区块高度
          required: true
          allowEmptyValue: false
          schema:
            type: integer
            format: int64
            example: 12475
      summary: 通过高度拉取区块
      description: 传入区块高度， 获取区块信息
      operationId: getBlockByHeight
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'
        '404':
          description: Block is not found
  /block/hash/{hash}:
    get:
      tags:
        - Block
      parameters:
        - name: hash
          in: path
          description: 所需获取区块的区块哈希
          required: true
          allowEmptyValue: false
          schema:
            type: string
      summary: 通过区块的哈希值获取对应区块
      description: 通过区块的哈希值获取对应区块
      operationId: getBlockByHash
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'
        '404':
          description: Block is not found
  /block/latest:
    get:
      tags:
        - Block
      summary: 获取最新的区块
      operationId: getLatestBlock
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'
        '400':
          description: Get latest block error
  /transaction/{tx_hash}:
    get:
      tags:
        - Transaction
      parameters:
        - name: tx_hash
          in: path
          description: 所需获取交易的交易哈希值
          required: true
          allowEmptyValue: false
          schema:
            type: string
      summary: 通过交易哈希值获取交易的相关信息
      description: 通过交易哈希值获取交易的相关信息
      operationId: getTransaction
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '404':
          description: Transaction not found
  /transaction/submit:
    post:
      tags:
        - Transaction
      summary: 提交交易到当前节点
      description: 将将以提交到节点
      operationId: submitTransaction
      responses:
        '202':
          description: Transaction submitted
        '400':
          description: Transaction verify failed
      requestBody:
        $ref: '#/components/requestBodies/SignedTransaction'
  /address/utxos/{address}:
    get:
      tags:
        - Address
      parameters:
        - name: address
          in: path
          description: 所需要获取utxo的地址
          required: true
          allowEmptyValue: false
          schema:
            type: string
      summary: 通过地址获取得到utxo
      description: 通过地址获取得到utxo
      operationId: getAddressUtxo
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Utxo'
components:
  schemas:
    NodeStatus:
      type: object
      properties:
        time:
          type: string
          format: date-time
          example: 2022-01-22T07:57:57Z
        height:
          type: integer
          format: int64
          example: 102482
    BlockHeader:
      type: object
      properties:
        hash:
          type: string
          example: 898434381f7ba8561c43acbea15f42e78793615d848b3bdd21c346bcc348bf70
        merkele_root:
          type: string
          example: 4aaf432ec97e907515970f8fc8d8061a3ed492972fa05853dff99a14f23b74c0
        height:
          type: integer
          example: 1
        prev_block_hash:
          type: string
          example: 5927506bf3b945c4bf8c1146466192e6bfaf57ec50912d7d4b72e5564f90089b
    Block:
      type: object
      properties:
        blockheader:
          $ref: '#/components/schemas/BlockHeader'
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Transaction:
      type: object
      properties:
        hash:
          type: string
        address:
          type: string
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/Input'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/Output'
    Input:
      type: object
    Output:
      type: object
      properties:
        index:
          type: integer
          description: 交易输出所在输出的index
        pub_key_hash:
          type: string
          description: 钱包地址
        value:
          type: integer
    SignedInput:
      type: object
      properties:
        tx_hash:
          type: string
          description: 输入交易的哈希值
        index:
          type: integer
          description: 输入交易所在输出的index
        signature:
          type: string
          description: 签名信息
    SignedOutput:
      type: object
      properties:
        value:
          type: integer
          description: 交易的输出
        pub_key_hash:
          type: string
          description: 交易输出的地址
    Utxo:
      type: object
      properties:
        index:
          type: integer
        output:
          $ref: '#/components/schemas/Output'
        tx_hash:
          type: string
    SignedTransaction:
      type: object
      properties:
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/SignedInput'
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/SignedOutput'
        tx_hash:
          type: string
  requestBodies:
    SignedTransaction:
      content:
        application/json:
          schema:
            allOf:
              - description: Signed Transaction
              - $ref: '#/components/schemas/SignedTransaction'