# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc.grpc import address_pb2 as rpc_dot_protos_dot_address__pb2


class AddressStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_address_utxo = channel.unary_unary(
                '/Address/get_address_utxo',
                request_serializer=rpc_dot_protos_dot_address__pb2.UtxoRequest.SerializeToString,
                response_deserializer=rpc_dot_protos_dot_address__pb2.UtxoRespond.FromString,
                )


class AddressServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_address_utxo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddressServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_address_utxo': grpc.unary_unary_rpc_method_handler(
                    servicer.get_address_utxo,
                    request_deserializer=rpc_dot_protos_dot_address__pb2.UtxoRequest.FromString,
                    response_serializer=rpc_dot_protos_dot_address__pb2.UtxoRespond.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Address', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Address(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_address_utxo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Address/get_address_utxo',
            rpc_dot_protos_dot_address__pb2.UtxoRequest.SerializeToString,
            rpc_dot_protos_dot_address__pb2.UtxoRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
