# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/protos/address.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18rpc/protos/address.proto\"/\n\x0bUtxoRequest\x12\x14\n\x07\x61\x64\x64ress\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_address\"K\n\x0bUtxoRespond\x12\x13\n\x06status\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05utxos\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_statusB\x08\n\x06_utxos29\n\x07\x41\x64\x64ress\x12.\n\x10get_address_utxo\x12\x0c.UtxoRequest\x1a\x0c.UtxoRespondb\x06proto3')



_UTXOREQUEST = DESCRIPTOR.message_types_by_name['UtxoRequest']
_UTXORESPOND = DESCRIPTOR.message_types_by_name['UtxoRespond']
UtxoRequest = _reflection.GeneratedProtocolMessageType('UtxoRequest', (_message.Message,), {
  'DESCRIPTOR' : _UTXOREQUEST,
  '__module__' : 'rpc.protos.address_pb2'
  # @@protoc_insertion_point(class_scope:UtxoRequest)
  })
_sym_db.RegisterMessage(UtxoRequest)

UtxoRespond = _reflection.GeneratedProtocolMessageType('UtxoRespond', (_message.Message,), {
  'DESCRIPTOR' : _UTXORESPOND,
  '__module__' : 'rpc.protos.address_pb2'
  # @@protoc_insertion_point(class_scope:UtxoRespond)
  })
_sym_db.RegisterMessage(UtxoRespond)

_ADDRESS = DESCRIPTOR.services_by_name['Address']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UTXOREQUEST._serialized_start=28
  _UTXOREQUEST._serialized_end=75
  _UTXORESPOND._serialized_start=77
  _UTXORESPOND._serialized_end=152
  _ADDRESS._serialized_start=154
  _ADDRESS._serialized_end=211
# @@protoc_insertion_point(module_scope)
