# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc.grpc import transaction_pb2 as rpc_dot_protos_dot_transaction__pb2


class TransactionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_transaction = channel.unary_unary(
                '/Transaction/get_transaction',
                request_serializer=rpc_dot_protos_dot_transaction__pb2.GetTransactionRequest.SerializeToString,
                response_deserializer=rpc_dot_protos_dot_transaction__pb2.GetTransactionRespond.FromString,
                )
        self.submit_transaction = channel.unary_unary(
                '/Transaction/submit_transaction',
                request_serializer=rpc_dot_protos_dot_transaction__pb2.SubmitTransactionRequest.SerializeToString,
                response_deserializer=rpc_dot_protos_dot_transaction__pb2.SubmitTransactionRespond.FromString,
                )


class TransactionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_transaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submit_transaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransactionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_transaction': grpc.unary_unary_rpc_method_handler(
                    servicer.get_transaction,
                    request_deserializer=rpc_dot_protos_dot_transaction__pb2.GetTransactionRequest.FromString,
                    response_serializer=rpc_dot_protos_dot_transaction__pb2.GetTransactionRespond.SerializeToString,
            ),
            'submit_transaction': grpc.unary_unary_rpc_method_handler(
                    servicer.submit_transaction,
                    request_deserializer=rpc_dot_protos_dot_transaction__pb2.SubmitTransactionRequest.FromString,
                    response_serializer=rpc_dot_protos_dot_transaction__pb2.SubmitTransactionRespond.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Transaction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transaction(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_transaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Transaction/get_transaction',
            rpc_dot_protos_dot_transaction__pb2.GetTransactionRequest.SerializeToString,
            rpc_dot_protos_dot_transaction__pb2.GetTransactionRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def submit_transaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Transaction/submit_transaction',
            rpc_dot_protos_dot_transaction__pb2.SubmitTransactionRequest.SerializeToString,
            rpc_dot_protos_dot_transaction__pb2.SubmitTransactionRespond.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
