# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/protos/transaction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1crpc/protos/transaction.proto\"3\n\x15GetTransactionRequest\x12\x11\n\x04hash\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_hash\"a\n\x15GetTransactionRespond\x12\x13\n\x06status\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x18\n\x0btransaction\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_statusB\x0e\n\x0c_transaction\"P\n\x18SubmitTransactionRequest\x12\x1e\n\x11signedTransaction\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x14\n\x12_signedTransaction\":\n\x18SubmitTransactionRespond\x12\x13\n\x06status\x18\x01 \x01(\x05H\x00\x88\x01\x01\x42\t\n\x07_status2\x9c\x01\n\x0bTransaction\x12\x41\n\x0fget_transaction\x12\x16.GetTransactionRequest\x1a\x16.GetTransactionRespond\x12J\n\x12submit_transaction\x12\x19.SubmitTransactionRequest\x1a\x19.SubmitTransactionRespondb\x06proto3')



_GETTRANSACTIONREQUEST = DESCRIPTOR.message_types_by_name['GetTransactionRequest']
_GETTRANSACTIONRESPOND = DESCRIPTOR.message_types_by_name['GetTransactionRespond']
_SUBMITTRANSACTIONREQUEST = DESCRIPTOR.message_types_by_name['SubmitTransactionRequest']
_SUBMITTRANSACTIONRESPOND = DESCRIPTOR.message_types_by_name['SubmitTransactionRespond']
GetTransactionRequest = _reflection.GeneratedProtocolMessageType('GetTransactionRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTRANSACTIONREQUEST,
  '__module__' : 'rpc.protos.transaction_pb2'
  # @@protoc_insertion_point(class_scope:GetTransactionRequest)
  })
_sym_db.RegisterMessage(GetTransactionRequest)

GetTransactionRespond = _reflection.GeneratedProtocolMessageType('GetTransactionRespond', (_message.Message,), {
  'DESCRIPTOR' : _GETTRANSACTIONRESPOND,
  '__module__' : 'rpc.protos.transaction_pb2'
  # @@protoc_insertion_point(class_scope:GetTransactionRespond)
  })
_sym_db.RegisterMessage(GetTransactionRespond)

SubmitTransactionRequest = _reflection.GeneratedProtocolMessageType('SubmitTransactionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITTRANSACTIONREQUEST,
  '__module__' : 'rpc.protos.transaction_pb2'
  # @@protoc_insertion_point(class_scope:SubmitTransactionRequest)
  })
_sym_db.RegisterMessage(SubmitTransactionRequest)

SubmitTransactionRespond = _reflection.GeneratedProtocolMessageType('SubmitTransactionRespond', (_message.Message,), {
  'DESCRIPTOR' : _SUBMITTRANSACTIONRESPOND,
  '__module__' : 'rpc.protos.transaction_pb2'
  # @@protoc_insertion_point(class_scope:SubmitTransactionRespond)
  })
_sym_db.RegisterMessage(SubmitTransactionRespond)

_TRANSACTION = DESCRIPTOR.services_by_name['Transaction']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETTRANSACTIONREQUEST._serialized_start=32
  _GETTRANSACTIONREQUEST._serialized_end=83
  _GETTRANSACTIONRESPOND._serialized_start=85
  _GETTRANSACTIONRESPOND._serialized_end=182
  _SUBMITTRANSACTIONREQUEST._serialized_start=184
  _SUBMITTRANSACTIONREQUEST._serialized_end=264
  _SUBMITTRANSACTIONRESPOND._serialized_start=266
  _SUBMITTRANSACTIONRESPOND._serialized_end=324
  _TRANSACTION._serialized_start=327
  _TRANSACTION._serialized_end=483
# @@protoc_insertion_point(module_scope)
